### ISSUE TITLE
Support for creating high-contrast icons

### ISSUE THREAD

**Issue by pke** [McFizh/iconcreator#1]
This feature is missing in almost all icon generators I've checked so far.

**Comment by McFizh** [comment]
Could you specify what kind of functionality you think this app would need to support high-contrast icons?

**Comment by pke** [comment]
Well for every icon/splashscreen that is created it could create a mono-chrome version of the icon/splashscreen and save it according to the specs here https://msdn.microsoft.com/en-us/library/windows/apps/hh965372.aspx

For black contrast it would have to have a black background and white front color, and for white contrast the opposite.
